import sodium from "libsodium-wrappers";

// GitHub's documented recipe for encrypting a value for the Actions secrets
// API: https://docs.github.com/en/rest/guides/encrypting-secrets-for-the-rest-api
export async function encryptSecretForGithub(publicKeyBase64: string, secretValue: string): Promise<string> {
  await sodium.ready;
  const binKey = sodium.from_base64(publicKeyBase64, sodium.base64_variants.ORIGINAL);
  const binSec = sodium.from_string(secretValue);
  const encrypted = sodium.crypto_box_seal(binSec, binKey);
  return sodium.to_base64(encrypted, sodium.base64_variants.ORIGINAL);
}

const WORKFLOW_PATH = ".github/workflows/codemoat.yml";

function workflowYaml(): string {
  return `name: CodeMoat

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: SYCO7/codemoat@v1
        with:
          api-key: \${{ secrets.CODEMOAT_API_KEY }}
`;
}

export interface AutoSetupResult {
  secretCreated: boolean;
  workflowCreated: boolean;
  workflowAlreadyExisted: boolean;
  warning?: string;
}

// Best-effort: wires up the repo secret + workflow file via the GitHub API
// using the user's own OAuth token (repo scope). Never throws — the repo is
// already connected and the key already generated by the time this runs, so
// a partial/total failure here should degrade to "show manual instructions",
// not fail the whole connect flow.
export async function autoSetupRepo(
  githubToken: string,
  owner: string,
  repo: string,
  apiKey: string
): Promise<AutoSetupResult> {
  const gh = (path: string, init?: RequestInit) =>
    fetch(`https://api.github.com${path}`, {
      ...init,
      headers: {
        authorization: `Bearer ${githubToken}`,
        accept: "application/vnd.github+json",
        "content-type": "application/json",
        ...init?.headers,
      },
    });

  let secretCreated = false;
  let workflowCreated = false;
  let workflowAlreadyExisted = false;
  const warnings: string[] = [];

  try {
    const pubKeyRes = await gh(`/repos/${owner}/${repo}/actions/secrets/public-key`);
    if (!pubKeyRes.ok) throw new Error(`public-key fetch failed (${pubKeyRes.status})`);
    const { key, key_id } = (await pubKeyRes.json()) as { key: string; key_id: string };

    const encrypted = await encryptSecretForGithub(key, apiKey);
    const secretRes = await gh(`/repos/${owner}/${repo}/actions/secrets/CODEMOAT_API_KEY`, {
      method: "PUT",
      body: JSON.stringify({ encrypted_value: encrypted, key_id }),
    });
    if (!secretRes.ok && secretRes.status !== 201 && secretRes.status !== 204) {
      throw new Error(`secret create failed (${secretRes.status})`);
    }
    secretCreated = true;
  } catch (err) {
    warnings.push(`secret: ${err instanceof Error ? err.message : String(err)}`);
  }

  try {
    const existingRes = await gh(`/repos/${owner}/${repo}/contents/${WORKFLOW_PATH}`);
    if (existingRes.ok) {
      workflowAlreadyExisted = true;
    } else if (existingRes.status === 404) {
      const createRes = await gh(`/repos/${owner}/${repo}/contents/${WORKFLOW_PATH}`, {
        method: "PUT",
        body: JSON.stringify({
          message: "Add CodeMoat security scanning",
          content: Buffer.from(workflowYaml()).toString("base64"),
        }),
      });
      if (!createRes.ok) throw new Error(`workflow create failed (${createRes.status})`);
      workflowCreated = true;
    } else {
      throw new Error(`workflow lookup failed (${existingRes.status})`);
    }
  } catch (err) {
    warnings.push(`workflow: ${err instanceof Error ? err.message : String(err)}`);
  }

  return {
    secretCreated,
    workflowCreated,
    workflowAlreadyExisted,
    warning: warnings.length ? warnings.join("; ") : undefined,
  };
}
